### ISSUE TITLE
Syntax Error for numbers function

### ISSUE THREAD

**Issue by curreta** [mcauser/micropython-tm1637#1]
Hey! Thanks for making this great utility.

I get ```ampy.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 11, in <module>\r\n  File "tm1637.py", line 129\r\nSyntaxError: invalid syntax\r\n')```

when trying to call the numbers function.

**Comment by mcauser** [comment]
Fixed at a59aa05cdc3375cd8946f2702d5085963817dc6c

**Comment by curreta** [comment]
@mcauser thank you! still learning python syntax so I can't catch simple fixes like that =P
