### ISSUE TITLE
Why not use hardware I2C?

### ISSUE THREAD

**Issue by nandlab** [mcauser/micropython-tm1637#14]
Hi there,
I looked at your source code and I wondered, is there any reason why you do not use a machine I2C API, for example the [I2C](https://docs.micropython.org/en/latest/library/machine.I2C.html) class from MicroPython or [smbus](https://pypi.org/project/smbus2/)? Instead you are bit-banging in software.

**Comment by Jomarra96** [comment]
Hey, apparently the comm protocol is not quite I2C, as you don't really R/W data into addresses. It's an obscure one, not widely supported. But just check the datasheet for more info
