### ISSUE TITLE
TM1637 init ValueError

### ISSUE THREAD

**Issue by VipSaran** [mcauser/micropython-tm1637#4]
Hi,

can you tell me what could be the problem behind this:

```
>>> import tm1637
>>> from machine import Pin 
>>> tm = tm1637.TM1637(clk=Pin(5), dio=Pin(4)) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid argument(s) value
```

Tested on: MicroPython v1.9.4 on 2018-05-11; WiPy with CC3200

**Comment by mcauser** [comment]
There is a `ValueError` on the brightness validation in `init()`, but it should be defaulting to 7 (max).

Does `ValueError` work on the wipy port?

If you run this in the REPL, do you set the same invalid args error?
`raise ValueError("Brightness out of range")`

**Comment by VipSaran** [comment]
REPL:

```
>>> raise ValueError("Brightness out of range")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Brightness out of range
>>> 
```

**Comment by mcauser** [comment]
Maybe try using the GP pin naming convention and dropping the named arguments. Eg.
`tm = tm1637.TM1637(Pin(‘GP10’), Pin(‘GP9’))`

**Comment by VipSaran** [comment]
`tm = tm1637.TM1637(clk=Pin('GP5'), dio=Pin('GP4'))` did the trick. Thanks :)
