### ISSUE TITLE
Clear method

### ISSUE THREAD

**Issue by thijstriemstra** [mcauser/micropython-tm1637#7]
How do I clear the screen completely? Can you add a `clear` or `reset` method?

Eg. this shows `1OOL, 2OOL` etc..

```python
>>> t.show('COOL')
>>> import utime
>>> for x in range(1000):
...     t.show(str(x))
...     utime.sleep(0.4)
```

`t.show('')` doesn't seem to work.

**Comment by mcauser** [comment]
There’s a bunch of examples in tm1637_test.py
Here’s how you can clear the display:
```
# all LEDS off
tm.write([0, 0, 0, 0])
tm.show('    ')
```

**Comment by thijstriemstra** [comment]
thanks.
